=== Drakopoullos/Aion-Core-4.8-SRC/AC-Tools/WDS-Generator/world_drop_generator48/data/static_data/world_drops.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="world_drop" type="worldDrop"/>

  <xs:element name="world_drops" type="worldDropData"/>

  <xs:complexType name="worldDropData">
    <xs:sequence>
      <xs:element ref="world_drop" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="worldDrop">
    <xs:sequence>
      <xs:element name="pattern" type="pattern"/>
    </xs:sequence>
    <xs:attribute name="chance" type="xs:float" use="required"/>
	<xs:attribute name="add_untradeable" type="xs:boolean"/>
    <xs:attribute name="race_restriction" type="race_restriction"/>
    <xs:attribute name="dropGroup" type="xs:string" use="required"/>
    <xs:attribute name="min_amount" type="xs:int" use="optional" default="1"/>
    <xs:attribute name="max_amount" type="xs:int" use="optional" default="1"/>
  </xs:complexType>

  <xs:complexType name="pattern" abstract="true">
    <xs:sequence/>
  </xs:complexType>

  <xs:complexType name="and_pattern">
    <xs:complexContent>
      <xs:extension base="pattern">
        <xs:sequence>
          <xs:element name="pattern" type="pattern" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="or_pattern">
    <xs:complexContent>
      <xs:extension base="pattern">
        <xs:sequence>
          <xs:element name="pattern" type="pattern" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="not_pattern">
    <xs:complexContent>
      <xs:extension base="pattern">
        <xs:sequence>
          <xs:element name="pattern" type="pattern" minOccurs="0"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="npc_rank">
    <xs:complexContent>
      <xs:extension base="pattern">
        <xs:sequence/>
        <xs:attribute name="rank" type="rank"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="npc_id">
    <xs:complexContent>
      <xs:extension base="pattern">
        <xs:sequence/>
        <xs:attribute name="npc_id" type="xs:int" use="required"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="npc_map_id">
    <xs:complexContent>
      <xs:extension base="pattern">
        <xs:sequence/>
        <xs:attribute name="map_ids" type="NumberListType" use="required"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="npc_item_lvl_diff">
    <xs:complexContent>
      <xs:extension base="pattern">
        <xs:sequence/>
        <xs:attribute name="min_dif" type="xs:int" use="required"/>
        <xs:attribute name="max_dif" type="xs:int" use="required"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="npc_level">
    <xs:complexContent>
      <xs:extension base="pattern">
        <xs:sequence/>
        <xs:attribute name="min_level" type="xs:int" use="required"/>
        <xs:attribute name="max_level" type="xs:int" use="required"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="npc_name">
    <xs:complexContent>
      <xs:extension base="stringPattern">
        <xs:sequence/>
        <xs:attribute name="val" type="xs:string"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="stringPattern" abstract="true">
    <xs:complexContent>
      <xs:extension base="pattern">
        <xs:sequence>
          <xs:element name="function" type="stringFunction" minOccurs="0"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="stringFunction" abstract="true">
    <xs:sequence/>
  </xs:complexType>

  <xs:complexType name="contains">
    <xs:complexContent>
      <xs:extension base="stringFunction">
        <xs:sequence/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="start_with">
    <xs:complexContent>
      <xs:extension base="stringFunction">
        <xs:sequence/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="end_with">
    <xs:complexContent>
      <xs:extension base="stringFunction">
        <xs:sequence/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="npc_race">
    <xs:complexContent>
      <xs:extension base="pattern">
        <xs:sequence/>
        <xs:attribute name="race" type="race"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="npc_rating">
    <xs:complexContent>
      <xs:extension base="pattern">
        <xs:sequence/>
        <xs:attribute name="rating" type="rating"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="item_cat">
    <xs:complexContent>
      <xs:extension base="pattern">
        <xs:sequence/>
        <xs:attribute name="category" type="item_category"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="item_ids">
    <xs:complexContent>
      <xs:extension base="pattern">
        <xs:sequence/>
        <xs:attribute name="item_ids" type="NumberListType" use="required"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
	<xs:simpleType name="NumberListType">
		<xs:list itemType="xs:int"/>
	</xs:simpleType>
  <xs:complexType name="item_level">
    <xs:complexContent>
      <xs:extension base="pattern">
        <xs:sequence/>
        <xs:attribute name="min_level" type="xs:int" use="required"/>
        <xs:attribute name="max_level" type="xs:int" use="required"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="item_name">
    <xs:complexContent>
      <xs:extension base="stringPattern">
        <xs:sequence/>
        <xs:attribute name="val" type="xs:string"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="item_quality">
    <xs:complexContent>
      <xs:extension base="pattern">
        <xs:sequence/>
        <xs:attribute name="quality" type="quality"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:simpleType name="race_restriction">
    <xs:restriction base="xs:string">
      <xs:enumeration value="ASMODIANS"/>
      <xs:enumeration value="ELYOS"/>
      <xs:enumeration value="NONE"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="rank">
    <xs:restriction base="xs:string">
      <xs:enumeration value="NOVICE"/>
      <xs:enumeration value="DISCIPLINED"/>
      <xs:enumeration value="SEASONED"/>
      <xs:enumeration value="EXPERT"/>
      <xs:enumeration value="VETERAN"/>
      <xs:enumeration value="MASTER"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="race">
    <xs:restriction base="xs:string">
      <xs:enumeration value="ELYOS"/>
      <xs:enumeration value="ASMODIANS"/>
      <xs:enumeration value="LYCAN"/>
      <xs:enumeration value="CONSTRUCT"/>
      <xs:enumeration value="CARRIER"/>
      <xs:enumeration value="DRAKAN"/>
      <xs:enumeration value="LIZARDMAN"/>
      <xs:enumeration value="TELEPORTER"/>
      <xs:enumeration value="NAGA"/>
      <xs:enumeration value="BROWNIE"/>
      <xs:enumeration value="KRALL"/>
      <xs:enumeration value="SHULACK"/>
      <xs:enumeration value="BARRIER"/>
      <xs:enumeration value="PC_LIGHT_CASTLE_DOOR"/>
      <xs:enumeration value="PC_DARK_CASTLE_DOOR"/>
      <xs:enumeration value="DRAGON_CASTLE_DOOR"/>
      <xs:enumeration value="GCHIEF_LIGHT"/>
      <xs:enumeration value="GCHIEF_DARK"/>
      <xs:enumeration value="DRAGON"/>
      <xs:enumeration value="OUTSIDER"/>
      <xs:enumeration value="RATMAN"/>
      <xs:enumeration value="DEMIHUMANOID"/>
      <xs:enumeration value="UNDEAD"/>
      <xs:enumeration value="BEAST"/>
      <xs:enumeration value="MAGICALMONSTER"/>
      <xs:enumeration value="ELEMENTAL"/>
      <xs:enumeration value="LIVINGWATER"/>
      <xs:enumeration value="NONE"/>
      <xs:enumeration value="PC_ALL"/>
      <xs:enumeration value="DEFORM"/>
      <xs:enumeration value="NEUT"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="rating">
    <xs:restriction base="xs:string">
      <xs:enumeration value="JUNK"/>
      <xs:enumeration value="NORMAL"/>
      <xs:enumeration value="ELITE"/>
      <xs:enumeration value="HERO"/>
      <xs:enumeration value="LEGENDARY"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="item_category">
    <xs:restriction base="xs:string">
      <xs:enumeration value="MANASTONE"/>
			<xs:enumeration value="SPECIAL_MANASTONE"/>
			<xs:enumeration value="GODSTONE"/>
			<xs:enumeration value="ENCHANTMENT"/>
			<xs:enumeration value="FLUX"/>
			<xs:enumeration value="BALIC_EMOTION"/>
			<xs:enumeration value="BALIC_MATERIAL"/>
			<xs:enumeration value="RAWHIDE"/>
			<xs:enumeration value="SOULSTONE"/>
			<xs:enumeration value="RECIPE"/>
			<xs:enumeration value="GATHERABLE"/>
			<xs:enumeration value="GATHERABLE_BONUS"/>
			<xs:enumeration value="DROP_MATERIAL"/>
			<xs:enumeration value="SWORD"/>
			<xs:enumeration value="DAGGER"/>
			<xs:enumeration value="MACE"/>
			<xs:enumeration value="ORB"/>
			<xs:enumeration value="SPELLBOOK"/>
			<xs:enumeration value="GREATSWORD"/>
			<xs:enumeration value="POLEARM"/>
			<xs:enumeration value="STAFF"/>
			<xs:enumeration value="BOW"/>
			<xs:enumeration value="SHIELD"/>
			<xs:enumeration value="HARP"/>
			<xs:enumeration value="GUN"/>
			<xs:enumeration value="CANNON"/>
			<xs:enumeration value="KEYBLADE"/>
			<xs:enumeration value="JACKET"/>
			<xs:enumeration value="PANTS"/>
			<xs:enumeration value="SHARD"/>
			<xs:enumeration value="SHOES"/>
			<xs:enumeration value="GLOVES"/>
			<xs:enumeration value="SHOULDERS"/>
			<xs:enumeration value="NECKLACE"/>
			<xs:enumeration value="EARRINGS"/>
			<xs:enumeration value="RINGS"/>
			<xs:enumeration value="HELMET"/>
			<xs:enumeration value="BELT"/>
			<xs:enumeration value="SKILLBOOK"/>
			<xs:enumeration value="STIGMA"/>
			<xs:enumeration value="COINS"/>
			<xs:enumeration value="MEDALS"/>
			<xs:enumeration value="QUEST"/>
			<xs:enumeration value="KEY"/>
			<xs:enumeration value="CRAFT_BOOST"/>
			<xs:enumeration value="COMBINATION"/>
			<xs:enumeration value="NONE"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="quality">
    <xs:restriction base="xs:string">
      <xs:enumeration value="COMMON"/>
      <xs:enumeration value="RARE"/>
      <xs:enumeration value="UNIQUE"/>
      <xs:enumeration value="LEGEND"/>
      <xs:enumeration value="MYTHIC"/>
      <xs:enumeration value="EPIC"/>
      <xs:enumeration value="JUNK"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== Drakopoullos/Aion-Core-4.8-SRC/AC-Tools/WDS-Generator/world_drop_generator48/data/static_data/world_drops.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<world_drops xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="world_drops.xsd">
	<!-- ENHANCMENT ITEMS -->
	<!-- Manastones -->
	<world_drop dropGroup="MANASTONE_COMMON" chance="15">
		<pattern xsi:type="and_pattern">
			<pattern xsi:type="npc_item_lvl_diff" min_dif="-9" max_dif="0"/>
			<pattern xsi:type="item_cat" category="MANASTONE"/>
			<pattern xsi:type="item_quality" quality="COMMON"/>
			<pattern xsi:type="item_level" min_level="10" max_level="60"/>
		</pattern>
	</world_drop>
	<world_drop dropGroup="MANASTONE_COMMON" chance="7">
		<pattern xsi:type="and_pattern">
			<pattern xsi:type="npc_item_lvl_diff" min_dif="-9" max_dif="10"/>
			<pattern xsi:type="item_cat" category="MANASTONE"/>
			<pattern xsi:type="item_name" val="Attack">
				<function xsi:type="contains"/>
			</pattern>
			<pattern xsi:type="item_quality" quality="COMMON"/>
			<pattern xsi:type="item_level" min_level="10" max_level="60"/>
		</pattern>
	</world_drop>
	<world_drop dropGroup="MANASTONE_RARE" chance="5">
		<pattern xsi:type="and_pattern">
			<pattern xsi:type="npc_item_lvl_diff" min_dif="-9" max_dif="0"/>
			<pattern xsi:type="item_cat" category="MANASTONE"/>
			<pattern xsi:type="item_quality" quality="RARE"/>
			<pattern xsi:type="item_level" min_level="20" max_level="60"/>
			<pattern xsi:type="not_pattern">
				<pattern xsi:type="item_ids" item_ids="167000563 167000465 167000497 167000523 167000559"/>
			</pattern>
		</pattern>
	</world_drop>
	<world_drop dropGroup="MANASTONE_RARE" chance="2">
		<pattern xsi:type="and_pattern">
			<pattern xsi:type="npc_item_lvl_diff" min_dif="-9" max_dif="10"/>
			<pattern xsi:type="item_cat" category="MANASTONE"/>
			<pattern xsi:type="item_name" val="Attack">
				<function xsi:type="contains"/>
			</pattern>
			<pattern xsi:type="item_quality" quality="RARE"/>
			<pattern xsi:type="item_level" min_level="10" max_level="60"/>
		</pattern>
	</world_drop>
	<!-- Godstones -->
	<world_drop dropGroup="GODSTONES" chance="0.005">
		<pattern xsi:type="and_pattern">
			<pattern xsi:type="npc_item_lvl_diff" min_dif="0" max_dif="10"/>
			<pattern xsi:type="item_cat" category="GODSTONE"/>
			<pattern xsi:type="item_quality" quality="LEGEND"/>
			<pattern xsi:type="item_level" min_level="40" max_level="55"/>
			<pattern xsi:type="not_pattern">
				<pattern xsi:type="item_ids" item_ids="168000037 168000040 168000038"/> <!-- 10% GS which are not dropable anymore on retail -->
			</pattern>
		</pattern>
	</world_drop>
	<world_drop dropGroup="GODSTONES" chance="0.001">
		<pattern xsi:type="and_pattern">
			<pattern xsi:type="npc_item_lvl_diff" min_dif="0" max_dif="10"/>
			<pattern xsi:type="item_cat" category="GODSTONE"/>
			<pattern xsi:type="item_quality" quality="UNIQUE"/>
			<pattern xsi:type="or_pattern">
				<pattern xsi:type="npc_rating" rating="ELITE"/>
				<pattern xsi:type="npc_rating" rating="HERO"/>
			</pattern>
			<pattern xsi:type="item_level" min_level="40" max_level="55"/>
		</pattern>
	</world_drop>
	<!-- Power Shards -->
	<world_drop dropGroup="POWER_SHARDS" min_amount="1" max_amount="5" chance="30">
		<pattern xsi:type="and_pattern">
			<pattern xsi:type="npc_item_lvl_diff" min_dif="0" max_dif="9"/>
			<pattern xsi:type="item_ids" item_ids="169000003 169000004 169000005 169000007 169000008 169000009"/>
		</pattern>
	</world_drop>
	<!-- Stigma Shards -->
	
	<!-- SKILLS -->
	<!-- Stigma -->
	<world_drop dropGroup="STIGMA" chance="1">
		<pattern xsi:type="and_pattern">
			<pattern xsi:type="npc_item_lvl_diff" min_dif="-1" max_dif="1"/>
			<pattern xsi:type="item_cat" category="STIGMA"/>
			<pattern xsi:type="item_quality" quality="RARE"/>
			<pattern xsi:type="item_level" min_level="20" max_level="60"/>
			<pattern xsi:type="not_pattern">
				<pattern xsi:type="item_ids" item_ids="140000095"/>
			</pattern>
		</pattern>
	</world_drop>
	<!-- Skill Books -->
	<!-- 42 -->
	<world_drop dropGroup="SKILL_BOOKS" chance="5">
		<pattern xsi:type="and_pattern">
			<pattern xsi:type="npc_item_lvl_diff" min_dif="0" max_dif="3"/>
			<pattern xsi:type="npc_map_id" map_ids="320110000 310050000" />
			<pattern xsi:type="item_ids" item_ids="169500698 169500699 169500095 169500096 169500596 169500597 169500499 169500432 169500258 169500338 169500157 169500257 169500156 169500433 169500500 169500337"/>
		</pattern>
	</world_drop>
	<!-- 46 -->
	<world_drop dropGroup="SKILL_BOOKS" chance="5">
		<pattern xsi:type="and_pattern">
			<pattern xsi:type="npc_item_lvl_diff" min_dif="-1" max_dif="4"/>
			<pattern xsi:type="npc_map_id" map_ids="210060000 220050000" />
			<pattern xsi:type="item_ids" item_ids="169500607 169500269 169500164 169500443 169500105 169500508 169500346 169500707"/>
		</pattern>
	</world_drop>
	<!-- 53 -->
	<world_drop dropGroup="SKILL_BOOKS" chance="5">
		<pattern xsi:type="and_pattern">
			<pattern xsi:type="npc_item_lvl_diff" min_dif="-1" max_dif="1"/>
			<pattern xsi:type="npc_map_id" map_ids="300150000 300160000" />
			<pattern xsi:type="item_ids" item_ids="169500842 169500861 169500818 169500785 169500877 169500803 169500830 169500774"/>
		</pattern>
	</world_drop>
	<!-- 54 -->
	<world_drop dropGroup="SKILL_BOOKS" chance="5">
		<pattern xsi:type="and_pattern">
			<pattern xsi:type="npc_item_lvl_diff" min_dif="-1" max_dif="4"/>
			<pattern xsi:type="npc_map_id" map_ids="210050000 220070000" />
			<pattern xsi:type="item_ids" item_ids="169500777 169500776 169500864 169500865 169500844 169500832 169500805 169500788 169500804 169500787 169500833 169500845"/>
		</pattern>
	</world_drop>
	
	<!-- CRAFT MATERIALS -->
	<!-- Flux -->
	<world_drop dropGroup="FLUX_COMMON" chance="8">
		<pattern xsi:type="and_pattern">
			<pattern xsi:type="item_level" min_level="13" max_level="60"/>
			<pattern xsi:type="npc_item_lvl_diff" min_dif="-2" max_dif="2"/>
			<pattern xsi:type="item_name" val="Flux">
				<function xsi:type="contains"/>
			</pattern>
			<pattern xsi:type="item_cat" category="FLUX"/>
			<pattern xsi:type="item_quality" quality="COMMON"/>
		</pattern>
	</world_drop>
	<world_drop dropGroup="FLUX_RARE" chance="4">
		<pattern xsi:type="and_pattern">
			<pattern xsi:type="item_level" min_level="23" max_level="60"/>
			<pattern xsi:type="npc_item_lvl_diff" min_dif="-2" max_dif="2"/>
			<pattern xsi:type="item_name" val="Flux">
				<function xsi:type="contains"/>
			</pattern>
			<pattern xsi:type="item_cat" category="FLUX"/>
			<pattern xsi:type="item_quality" quality="RARE"/>
		</pattern>
	</world_drop>
	<world_drop dropGroup="FLUX_LEGEND" chance="2">
		<pattern xsi:type="and_pattern">
			<pattern xsi:type="item_level" min_level="33" max_level="60"/>
			<pattern xsi:type="npc_item_lvl_diff" min_dif="-2" max_dif="2"/>
			<pattern xsi:type="item_name" val="Flux">
				<function xsi:type="contains"/>
			</pattern>
			<pattern xsi:type="item_cat" category="FLUX"/>
			<pattern xsi:type="item_quality" quality="LEGEND"/>
		</pattern>
	</world_drop>
	<world_drop dropGroup="FLUX_UNIQUE" chance="1">
		<pattern xsi:type="and_pattern">
			<pattern xsi:type="item_level" min_level="43" max_level="60"/>
			<pattern xsi:type="npc_item_lvl_diff" min_dif="-2" max_dif="2"/>
			<pattern xsi:type="item_name" val="Flux">
				<function xsi:type="contains"/>
			</pattern>
			<pattern xsi:type="item_cat" category="FLUX"/>
			<pattern xsi:type="item_quality" quality="UNIQUE"/>
		</pattern>
	</world_drop>
	<!-- Elemental Stones -->
	<world_drop dropGroup="ELEMENTAL_STONES" chance="25">
		<pattern xsi:type="and_pattern">
			<pattern xsi:type="npc_item_lvl_diff" min_dif="0" max_dif="9"/>
			<pattern xsi:type="item_ids" item_ids="152010314 152010315 152010316 152010317 152010319"/>
			<pattern xsi:type="or_pattern">
				<pattern xsi:type="npc_rating" rating="NORMAL"/>
				<pattern xsi:type="npc_rating" rating="ELITE"/>
				<pattern xsi:type="npc_rating" rating="HERO"/>
			</pattern>
			<pattern xsi:type="or_pattern">
				<pattern xsi:type="npc_race" race="BEAST"/>
				<pattern xsi:type="npc_race" race="MAGICALMONSTER"/>
				<pattern xsi:type="npc_race" race="ELEMENTAL"/>
				<pattern xsi:type="npc_race" race="UNDEAD"/>
				<pattern xsi:type="npc_race" race="DEMIHUMANOID"/>
				<pattern xsi:type="npc_race" race="LYCAN"/>
				<pattern xsi:type="npc_race" race="LIZARDMAN"/>
				<pattern xsi:type="npc_race" race="OUTSIDER"/>
			</pattern>
		</pattern>
	</world_drop>
	<!-- TODO : Raw -->
	
	<!-- Balic Materials -->
	<world_drop dropGroup="BALAUR_MATERIAL" chance="3">
		<pattern xsi:type="and_pattern">
			<pattern xsi:type="or_pattern">
				<pattern xsi:type="npc_race" race="DRAKAN"/>
				<pattern xsi:type="npc_race" race="DRAGON"/>
				<pattern xsi:type="npc_race" race="LIZARDMAN"/>
				<pattern xsi:type="npc_race" race="NAGA"/>
			</pattern>
			<pattern xsi:type="npc_item_lvl_diff" min_dif="-9" max_dif="0"/>
			<pattern xsi:type="item_ids" item_ids="186000032 186000033 186000097"/>
		</pattern>
	</world_drop>
	<world_drop dropGroup="BALAUR_BLOOD" chance="5">
		<pattern xsi:type="and_pattern">
			<pattern xsi:type="or_pattern">
				<pattern xsi:type="npc_race" race="DRAKAN"/>
				<pattern xsi:type="npc_race" race="DRAGON"/>
				<pattern xsi:type="npc_race" race="LIZARDMAN"/>
				<pattern xsi:type="npc_race" race="NAGA"/>
			</pattern>
			<pattern xsi:type="npc_item_lvl_diff" min_dif="-9" max_dif="10"/>
			<pattern xsi:type="item_ids" item_ids="152014019 152014014 152014009 152014004"/>
		</pattern>
	</world_drop>
	<world_drop dropGroup="BALAUR_SKIN" chance="5">
		<pattern xsi:type="and_pattern">
			<pattern xsi:type="or_pattern">
				<pattern xsi:type="npc_race" race="DRAKAN"/>
				<pattern xsi:type="npc_race" race="DRAGON"/>
				<pattern xsi:type="npc_race" race="LIZARDMAN"/>
				<pattern xsi:type="npc_race" race="NAGA"/>
			</pattern>
			<pattern xsi:type="npc_item_lvl_diff" min_dif="-9" max_dif="10"/>
			<pattern xsi:type="item_ids" item_ids="152014018 152014013 152014008 152014003"/>
		</pattern>
	</world_drop>
